### PR TITLE
Fixes planet node

### PR DESCRIPTION
**Pull request by svperfecta**
Hi @mikeal  - 

I heard on a podcast somewhere (nodeup?) that planetnode was down and you were looking for a new maintainer.  This pull request should fix it.  

Also, I setup new hosting for the site at Heroku here:
  planetnode.herokuapp.com

If you're comfortable, and would setup a CNAME, I'd like to maintain this going forward :)

### CODE REVIEW

**Comment by danmactough** [comment]
:+1: for using feedparser :smile:

**Comment by svperfecta** [comment]
Woot!  I think I'm going to move the disk cache into redis too.

On Sunday, April 6, 2014, Dan MacTough notifications@github.com wrote:

> [image: :+1:] for using feedparser [image: :smile:]
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mikeal/planet/pull/9#issuecomment-39657998
> .

## 

Brian Corrigan
MadGlory Interactive
http://www.madglory.com
Tw: @madgloryint
Ph: 518.867.1439

**Comment by mikeal** [comment]
@genexp, you are now a collaborator.

**Comment by svperfecta** [comment]
Thanks @mikael - Did you notice my other question on hosting?  Do you want
to continue to manage that or would you mind if I took that over.  I have
it running now on Heroku, with the caveat that I need to migrate the disk
based databased into something like redis in order to ensure it works long
term.

**Comment by mikeal** [comment]
Tell me where to point it and I'll point it :)

**Comment by svperfecta** [comment]
Cool.  If you could change the CNAME to planetnode.herokuapp.com I'll take
responsibility for keeping this up and running :)  I already made the
change on this side.

Glad this is working again!  Dunno, I sorta like planet sites.  It helps
new community members learn a bit about the lay of the land.

**Comment by svperfecta** [comment]
Apologies, its: planetnode.herokuapp.com

**Comment by mikeal** [comment]
had to make the root domain an A record so it's pointing at the IP.

**Comment by svperfecta** [comment]
Alright!  So for some reason, Heroku doesn't support apex domains.  In order to fake it (until they make it) if you'd:
- Add a cname for www.planetnodejs.com -> planetnode.herokuapp.com
- Add a A record pointing planetnodejs.com -> 174.129.25.170

We're all set!

**Comment by mikeal** [comment]
fixed.

**Pull request merged**
